include: package:very_good_analysis/analysis_options.yaml
linter:  
  rules:
    public_member_api_docs: false
    avoid_final_parameters: false
    lines_longer_than_80_chars: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
    



